/*
 * DNA Evolutions - JOpt.TourOptimizer
 *
 * This is DNA's JOpt.TourOptimizer service. A RESTful Spring Boot application using springdoc-openapi and OpenAPI 3. JOpt.TourOptimizer is a service that delivers route optimization and automatic scheduling features to be easily integrated into any third-party application. JOpt.TourOptimizer encapsulates all necessary optimization functionality and provides a comprehensive REST API that offers a domain-specific optimization interface for the transportation industry. The service is stateless and does not come with graphical user interfaces, map depiction or any databases. These extensions and adjustments are supposed to be introduced by the consumer of the service while integrating it into his/her own application. The service will allow for many suitable adjustments and user-specific settings to adjust the behaviour and optimization goals (e.g. minimizing distance, maximizing resource utilization, etc.) through a comprehensive set of functions. This will enable you to gain control of the complete optimization processes.This service is based on JOpt (7.5.1-rc3-j17-SNAPSHOT)
 *
 * The version of the OpenAPI document: unknown
 * Contact: info@dna-evolutions.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// The connectionRelatedLateMargin
    /// </summary>
    [DataContract(Name = "ConnectionRelatedLateMargin")]
    public partial class ConnectionRelatedLateMargin : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectionRelatedLateMargin" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ConnectionRelatedLateMargin() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectionRelatedLateMargin" /> class.
        /// </summary>
        /// <param name="shiftElementConnectionRealtedLateMargin">The isDoElementShiftConnectionRealtedLateMargin.</param>
        /// <param name="applyPartialConnectionRelatedLateMargin">The applyPartialConnectionRelatedLateMargin.</param>
        /// <param name="maxMargin">The maxMargin (required).</param>
        /// <param name="marginFactor">The marginFactor between 0 (inclusive) and 1 (inclusive) (required).</param>
        public ConnectionRelatedLateMargin(bool shiftElementConnectionRealtedLateMargin = default(bool), bool applyPartialConnectionRelatedLateMargin = default(bool), string maxMargin = default(string), double marginFactor = default(double))
        {
            // to ensure "maxMargin" is required (not null)
            if (maxMargin == null)
            {
                throw new ArgumentNullException("maxMargin is a required property for ConnectionRelatedLateMargin and cannot be null");
            }
            this.MaxMargin = maxMargin;
            this.MarginFactor = marginFactor;
            this.ShiftElementConnectionRealtedLateMargin = shiftElementConnectionRealtedLateMargin;
            this.ApplyPartialConnectionRelatedLateMargin = applyPartialConnectionRelatedLateMargin;
        }

        /// <summary>
        /// The isDoElementShiftConnectionRealtedLateMargin
        /// </summary>
        /// <value>The isDoElementShiftConnectionRealtedLateMargin</value>
        [DataMember(Name = "shiftElementConnectionRealtedLateMargin", EmitDefaultValue = true)]
        public bool ShiftElementConnectionRealtedLateMargin { get; set; }

        /// <summary>
        /// The applyPartialConnectionRelatedLateMargin
        /// </summary>
        /// <value>The applyPartialConnectionRelatedLateMargin</value>
        [DataMember(Name = "applyPartialConnectionRelatedLateMargin", EmitDefaultValue = true)]
        public bool ApplyPartialConnectionRelatedLateMargin { get; set; }

        /// <summary>
        /// The maxMargin
        /// </summary>
        /// <value>The maxMargin</value>
        /*
        <example>PT10M</example>
        */
        [DataMember(Name = "maxMargin", IsRequired = true, EmitDefaultValue = true)]
        public string MaxMargin { get; set; }

        /// <summary>
        /// The marginFactor between 0 (inclusive) and 1 (inclusive)
        /// </summary>
        /// <value>The marginFactor between 0 (inclusive) and 1 (inclusive)</value>
        /*
        <example>0.2</example>
        */
        [DataMember(Name = "marginFactor", IsRequired = true, EmitDefaultValue = true)]
        public double MarginFactor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConnectionRelatedLateMargin {\n");
            sb.Append("  ShiftElementConnectionRealtedLateMargin: ").Append(ShiftElementConnectionRealtedLateMargin).Append("\n");
            sb.Append("  ApplyPartialConnectionRelatedLateMargin: ").Append(ApplyPartialConnectionRelatedLateMargin).Append("\n");
            sb.Append("  MaxMargin: ").Append(MaxMargin).Append("\n");
            sb.Append("  MarginFactor: ").Append(MarginFactor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
