/*
 * DNA Evolutions - JOpt.TourOptimizer
 *
 * This is DNA's JOpt.TourOptimizer service. A RESTful Spring Boot application using springdoc-openapi and OpenAPI 3. JOpt.TourOpptimizer is a service that delivers route optimization and automatic scheduling features to be easily integrated into any third-party application. JOpt.TourOpptimizer encapsulates all necessary optimization functionality and provides a comprehensive REST API that offers a domain-specific optimization interface for the transportation industry. The service is stateless and does not come with graphical user interfaces, map depiction or any databases. These extensions and adjustments are supposed to be introduced by the consumer of the service while integrating it into his/her own application. The service will allow for many suitable adjustments and user-specific settings to adjust the behaviour and optimization goals (e.g. minimizing distance, maximizing resource utilization, etc.) through a comprehensive set of functions. This will enable you to gain control of the complete optimization processes.This service is based on JOpt (7.5.1-SNAPSHOT)
 *
 * The version of the OpenAPI document: 1.2.1-SNAPSHOT
 * Contact: info@dna-evolutions.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// The coreBuildOptions provided by the library
    /// </summary>
    [DataContract(Name = "CoreBuildOptions")]
    public partial class CoreBuildOptions : IEquatable<CoreBuildOptions>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CoreBuildOptions" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CoreBuildOptions() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CoreBuildOptions" /> class.
        /// </summary>
        /// <param name="buildCoreProperties">buildCoreProperties (required).</param>
        public CoreBuildOptions(CoreBuildOptionsBuildCoreProperties buildCoreProperties = default(CoreBuildOptionsBuildCoreProperties))
        {
            // to ensure "buildCoreProperties" is required (not null)
            if (buildCoreProperties == null)
            {
                throw new ArgumentNullException("buildCoreProperties is a required property for CoreBuildOptions and cannot be null");
            }
            this.BuildCoreProperties = buildCoreProperties;
        }

        /// <summary>
        /// Gets or Sets BuildCoreProperties
        /// </summary>
        [DataMember(Name = "buildCoreProperties", IsRequired = true, EmitDefaultValue = false)]
        public CoreBuildOptionsBuildCoreProperties BuildCoreProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CoreBuildOptions {\n");
            sb.Append("  BuildCoreProperties: ").Append(BuildCoreProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CoreBuildOptions);
        }

        /// <summary>
        /// Returns true if CoreBuildOptions instances are equal
        /// </summary>
        /// <param name="input">Instance of CoreBuildOptions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CoreBuildOptions input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.BuildCoreProperties == input.BuildCoreProperties ||
                    (this.BuildCoreProperties != null &&
                    this.BuildCoreProperties.Equals(input.BuildCoreProperties))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BuildCoreProperties != null)
                {
                    hashCode = (hashCode * 59) + this.BuildCoreProperties.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
