/*
 * DNA Evolutions - JOpt.TourOptimizer
 *
 * This is DNA's JOpt.TourOptimizer service. A RESTful Spring Boot application using springdoc-openapi and OpenAPI 3. JOpt.TourOpptimizer is a service that delivers route optimization and automatic scheduling features to be easily integrated into any third-party application. JOpt.TourOpptimizer encapsulates all necessary optimization functionality and provides a comprehensive REST API that offers a domain-specific optimization interface for the transportation industry. The service is stateless and does not come with graphical user interfaces, map depiction or any databases. These extensions and adjustments are supposed to be introduced by the consumer of the service while integrating it into his/her own application. The service will allow for many suitable adjustments and user-specific settings to adjust the behaviour and optimization goals (e.g. minimizing distance, maximizing resource utilization, etc.) through a comprehensive set of functions. This will enable you to gain control of the complete optimization processes.This service is based on JOpt (null)
 *
 * The version of the OpenAPI document: 1.2.2-SNAPSHOT
 * Contact: info@dna-evolutions.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// EdgeElementConnection
    /// </summary>
    [DataContract(Name = "EdgeElementConnection")]
    [JsonConverter(typeof(JsonSubtypes), "TypeName")]
    [JsonSubtypes.KnownSubType(typeof(EdgeElementConnection), "Edge")]
    public partial class EdgeElementConnection : ElementConnectionType, IEquatable<EdgeElementConnection>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdgeElementConnection" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EdgeElementConnection() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdgeElementConnection" /> class.
        /// </summary>
        /// <param name="distance">The distance of the connection. (required).</param>
        /// <param name="time">The time needed to pass the connection..</param>
        /// <param name="fromPosition">fromPosition.</param>
        /// <param name="toPosition">toPosition.</param>
        /// <param name="connectionByTime">connectionByTime.</param>
        /// <param name="typeName">The typeName of the object (required) (default to &quot;Edge&quot;).</param>
        public EdgeElementConnection(string distance = default(string), string time = default(string), Position fromPosition = default(Position), Position toPosition = default(Position), ConnectionByTime connectionByTime = default(ConnectionByTime), string typeName = "Edge") : base()
        {
            // to ensure "distance" is required (not null)
            if (distance == null)
            {
                throw new ArgumentNullException("distance is a required property for EdgeElementConnection and cannot be null");
            }
            this.Distance = distance;
            // to ensure "typeName" is required (not null)
            if (typeName == null)
            {
                throw new ArgumentNullException("typeName is a required property for EdgeElementConnection and cannot be null");
            }
            this.TypeName = typeName;
            this.Time = time;
            this.FromPosition = fromPosition;
            this.ToPosition = toPosition;
            this.ConnectionByTime = connectionByTime;
        }

        /// <summary>
        /// The distance of the connection.
        /// </summary>
        /// <value>The distance of the connection.</value>
        [DataMember(Name = "distance", IsRequired = true, EmitDefaultValue = false)]
        public string Distance { get; set; }

        /// <summary>
        /// The time needed to pass the connection.
        /// </summary>
        /// <value>The time needed to pass the connection.</value>
        [DataMember(Name = "time", EmitDefaultValue = false)]
        public string Time { get; set; }

        /// <summary>
        /// Gets or Sets FromPosition
        /// </summary>
        [DataMember(Name = "fromPosition", EmitDefaultValue = false)]
        public Position FromPosition { get; set; }

        /// <summary>
        /// Gets or Sets ToPosition
        /// </summary>
        [DataMember(Name = "toPosition", EmitDefaultValue = false)]
        public Position ToPosition { get; set; }

        /// <summary>
        /// Gets or Sets ConnectionByTime
        /// </summary>
        [DataMember(Name = "connectionByTime", EmitDefaultValue = false)]
        public ConnectionByTime ConnectionByTime { get; set; }

        /// <summary>
        /// The typeName of the object
        /// </summary>
        /// <value>The typeName of the object</value>
        [DataMember(Name = "typeName", IsRequired = true, EmitDefaultValue = false)]
        public string TypeName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdgeElementConnection {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Distance: ").Append(Distance).Append("\n");
            sb.Append("  Time: ").Append(Time).Append("\n");
            sb.Append("  FromPosition: ").Append(FromPosition).Append("\n");
            sb.Append("  ToPosition: ").Append(ToPosition).Append("\n");
            sb.Append("  ConnectionByTime: ").Append(ConnectionByTime).Append("\n");
            sb.Append("  TypeName: ").Append(TypeName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EdgeElementConnection);
        }

        /// <summary>
        /// Returns true if EdgeElementConnection instances are equal
        /// </summary>
        /// <param name="input">Instance of EdgeElementConnection to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EdgeElementConnection input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this.Distance == input.Distance ||
                    (this.Distance != null &&
                    this.Distance.Equals(input.Distance))
                ) && base.Equals(input) && 
                (
                    this.Time == input.Time ||
                    (this.Time != null &&
                    this.Time.Equals(input.Time))
                ) && base.Equals(input) && 
                (
                    this.FromPosition == input.FromPosition ||
                    (this.FromPosition != null &&
                    this.FromPosition.Equals(input.FromPosition))
                ) && base.Equals(input) && 
                (
                    this.ToPosition == input.ToPosition ||
                    (this.ToPosition != null &&
                    this.ToPosition.Equals(input.ToPosition))
                ) && base.Equals(input) && 
                (
                    this.ConnectionByTime == input.ConnectionByTime ||
                    (this.ConnectionByTime != null &&
                    this.ConnectionByTime.Equals(input.ConnectionByTime))
                ) && base.Equals(input) && 
                (
                    this.TypeName == input.TypeName ||
                    (this.TypeName != null &&
                    this.TypeName.Equals(input.TypeName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Distance != null)
                {
                    hashCode = (hashCode * 59) + this.Distance.GetHashCode();
                }
                if (this.Time != null)
                {
                    hashCode = (hashCode * 59) + this.Time.GetHashCode();
                }
                if (this.FromPosition != null)
                {
                    hashCode = (hashCode * 59) + this.FromPosition.GetHashCode();
                }
                if (this.ToPosition != null)
                {
                    hashCode = (hashCode * 59) + this.ToPosition.GetHashCode();
                }
                if (this.ConnectionByTime != null)
                {
                    hashCode = (hashCode * 59) + this.ConnectionByTime.GetHashCode();
                }
                if (this.TypeName != null)
                {
                    hashCode = (hashCode * 59) + this.TypeName.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
