/*
 * DNA Evolutions - JOpt.TourOptimizer
 *
 * This is DNA's JOpt.TourOptimizer service. A RESTful Spring Boot application using springdoc-openapi and OpenAPI 3. JOpt.TourOpptimizer is a service that delivers route optimization and automatic scheduling features to be easily integrated into any third-party application. JOpt.TourOpptimizer encapsulates all necessary optimization functionality and provides a comprehensive REST API that offers a domain-specific optimization interface for the transportation industry. The service is stateless and does not come with graphical user interfaces, map depiction or any databases. These extensions and adjustments are supposed to be introduced by the consumer of the service while integrating it into his/her own application. The service will allow for many suitable adjustments and user-specific settings to adjust the behaviour and optimization goals (e.g. minimizing distance, maximizing resource utilization, etc.) through a comprehensive set of functions. This will enable you to gain control of the complete optimization processes.This service is based on JOpt (7.5.1-SNAPSHOT)
 *
 * The version of the OpenAPI document: 1.2.1-SNAPSHOT
 * Contact: info@dna-evolutions.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// MultiTimeWindowNodeRelationAllOf
    /// </summary>
    [DataContract(Name = "MultiTimeWindowNodeRelation_allOf")]
    public partial class MultiTimeWindowNodeRelationAllOf : IEquatable<MultiTimeWindowNodeRelationAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MultiTimeWindowNodeRelationAllOf" /> class.
        /// </summary>
        /// <param name="typeName">The typeName of the object (default to &quot;MultiTimeWindow&quot;).</param>
        /// <param name="anchorDetails">The anchorDetails. The list of anchorDetails biasing the relation..</param>
        /// <param name="isNeedSameVisitor">Do we want the same visitor for all elements of the relation?.</param>
        /// <param name="isOverlapAllowed">Do we want to allow overlaps - makes sense if isNeedSameVisitor is false?.</param>
        public MultiTimeWindowNodeRelationAllOf(string typeName = "MultiTimeWindow", List<RouteElementDetail> anchorDetails = default(List<RouteElementDetail>), bool isNeedSameVisitor = default(bool), bool isOverlapAllowed = default(bool))
        {
            // use default value if no "typeName" provided
            this.TypeName = typeName ?? "MultiTimeWindow";
            this.AnchorDetails = anchorDetails;
            this.IsNeedSameVisitor = isNeedSameVisitor;
            this.IsOverlapAllowed = isOverlapAllowed;
        }

        /// <summary>
        /// The typeName of the object
        /// </summary>
        /// <value>The typeName of the object</value>
        [DataMember(Name = "typeName", EmitDefaultValue = false)]
        public string TypeName { get; set; }

        /// <summary>
        /// The anchorDetails. The list of anchorDetails biasing the relation.
        /// </summary>
        /// <value>The anchorDetails. The list of anchorDetails biasing the relation.</value>
        [DataMember(Name = "anchorDetails", EmitDefaultValue = false)]
        public List<RouteElementDetail> AnchorDetails { get; set; }

        /// <summary>
        /// Do we want the same visitor for all elements of the relation?
        /// </summary>
        /// <value>Do we want the same visitor for all elements of the relation?</value>
        [DataMember(Name = "isNeedSameVisitor", EmitDefaultValue = true)]
        public bool IsNeedSameVisitor { get; set; }

        /// <summary>
        /// Do we want to allow overlaps - makes sense if isNeedSameVisitor is false?
        /// </summary>
        /// <value>Do we want to allow overlaps - makes sense if isNeedSameVisitor is false?</value>
        [DataMember(Name = "isOverlapAllowed", EmitDefaultValue = true)]
        public bool IsOverlapAllowed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MultiTimeWindowNodeRelationAllOf {\n");
            sb.Append("  TypeName: ").Append(TypeName).Append("\n");
            sb.Append("  AnchorDetails: ").Append(AnchorDetails).Append("\n");
            sb.Append("  IsNeedSameVisitor: ").Append(IsNeedSameVisitor).Append("\n");
            sb.Append("  IsOverlapAllowed: ").Append(IsOverlapAllowed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MultiTimeWindowNodeRelationAllOf);
        }

        /// <summary>
        /// Returns true if MultiTimeWindowNodeRelationAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of MultiTimeWindowNodeRelationAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MultiTimeWindowNodeRelationAllOf input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TypeName == input.TypeName ||
                    (this.TypeName != null &&
                    this.TypeName.Equals(input.TypeName))
                ) && 
                (
                    this.AnchorDetails == input.AnchorDetails ||
                    this.AnchorDetails != null &&
                    input.AnchorDetails != null &&
                    this.AnchorDetails.SequenceEqual(input.AnchorDetails)
                ) && 
                (
                    this.IsNeedSameVisitor == input.IsNeedSameVisitor ||
                    this.IsNeedSameVisitor.Equals(input.IsNeedSameVisitor)
                ) && 
                (
                    this.IsOverlapAllowed == input.IsOverlapAllowed ||
                    this.IsOverlapAllowed.Equals(input.IsOverlapAllowed)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TypeName != null)
                {
                    hashCode = (hashCode * 59) + this.TypeName.GetHashCode();
                }
                if (this.AnchorDetails != null)
                {
                    hashCode = (hashCode * 59) + this.AnchorDetails.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.IsNeedSameVisitor.GetHashCode();
                hashCode = (hashCode * 59) + this.IsOverlapAllowed.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
