/*
 * DNA Evolutions - JOpt.TourOptimizer
 *
 * This is DNA's JOpt.TourOptimizer service. A RESTful Spring Boot application using springdoc-openapi and OpenAPI 3. JOpt.TourOpptimizer is a service that delivers route optimization and automatic scheduling features to be easily integrated into any third-party application. JOpt.TourOpptimizer encapsulates all necessary optimization functionality and provides a comprehensive REST API that offers a domain-specific optimization interface for the transportation industry. The service is stateless and does not come with graphical user interfaces, map depiction or any databases. These extensions and adjustments are supposed to be introduced by the consumer of the service while integrating it into his/her own application. The service will allow for many suitable adjustments and user-specific settings to adjust the behaviour and optimization goals (e.g. minimizing distance, maximizing resource utilization, etc.) through a comprehensive set of functions. This will enable you to gain control of the complete optimization processes.This service is based on JOpt (7.5.1-SNAPSHOT)
 *
 * The version of the OpenAPI document: 1.2.1-SNAPSHOT
 * Contact: info@dna-evolutions.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ResourceLocationConstraintAllOf
    /// </summary>
    [DataContract(Name = "ResourceLocationConstraint_allOf")]
    public partial class ResourceLocationConstraintAllOf : IEquatable<ResourceLocationConstraintAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceLocationConstraintAllOf" /> class.
        /// </summary>
        /// <param name="maxRadiusDistance">The maxRadiusDistance.</param>
        /// <param name="maxRadiusTime">The maxRadiusTime.</param>
        /// <param name="typeName">The typeName of the object (default to &quot;ResourceLocationConstraint&quot;).</param>
        public ResourceLocationConstraintAllOf(string maxRadiusDistance = default(string), string maxRadiusTime = default(string), string typeName = "ResourceLocationConstraint")
        {
            this.MaxRadiusDistance = maxRadiusDistance;
            this.MaxRadiusTime = maxRadiusTime;
            // use default value if no "typeName" provided
            this.TypeName = typeName ?? "ResourceLocationConstraint";
        }

        /// <summary>
        /// The maxRadiusDistance
        /// </summary>
        /// <value>The maxRadiusDistance</value>
        [DataMember(Name = "maxRadiusDistance", EmitDefaultValue = false)]
        public string MaxRadiusDistance { get; set; }

        /// <summary>
        /// The maxRadiusTime
        /// </summary>
        /// <value>The maxRadiusTime</value>
        [DataMember(Name = "maxRadiusTime", EmitDefaultValue = false)]
        public string MaxRadiusTime { get; set; }

        /// <summary>
        /// The typeName of the object
        /// </summary>
        /// <value>The typeName of the object</value>
        [DataMember(Name = "typeName", EmitDefaultValue = false)]
        public string TypeName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResourceLocationConstraintAllOf {\n");
            sb.Append("  MaxRadiusDistance: ").Append(MaxRadiusDistance).Append("\n");
            sb.Append("  MaxRadiusTime: ").Append(MaxRadiusTime).Append("\n");
            sb.Append("  TypeName: ").Append(TypeName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ResourceLocationConstraintAllOf);
        }

        /// <summary>
        /// Returns true if ResourceLocationConstraintAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of ResourceLocationConstraintAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ResourceLocationConstraintAllOf input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.MaxRadiusDistance == input.MaxRadiusDistance ||
                    (this.MaxRadiusDistance != null &&
                    this.MaxRadiusDistance.Equals(input.MaxRadiusDistance))
                ) && 
                (
                    this.MaxRadiusTime == input.MaxRadiusTime ||
                    (this.MaxRadiusTime != null &&
                    this.MaxRadiusTime.Equals(input.MaxRadiusTime))
                ) && 
                (
                    this.TypeName == input.TypeName ||
                    (this.TypeName != null &&
                    this.TypeName.Equals(input.TypeName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MaxRadiusDistance != null)
                {
                    hashCode = (hashCode * 59) + this.MaxRadiusDistance.GetHashCode();
                }
                if (this.MaxRadiusTime != null)
                {
                    hashCode = (hashCode * 59) + this.MaxRadiusTime.GetHashCode();
                }
                if (this.TypeName != null)
                {
                    hashCode = (hashCode * 59) + this.TypeName.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
