/*
 * DNA Evolutions - JOpt.TourOptimizer
 *
 * This is DNA's JOpt.TourOptimizer service. A RESTful Spring Boot application using springdoc-openapi and OpenAPI 3. JOpt.TourOpptimizer is a service that delivers route optimization and automatic scheduling features to be easily integrated into any third-party application. JOpt.TourOpptimizer encapsulates all necessary optimization functionality and provides a comprehensive REST API that offers a domain-specific optimization interface for the transportation industry. The service is stateless and does not come with graphical user interfaces, map depiction or any databases. These extensions and adjustments are supposed to be introduced by the consumer of the service while integrating it into his/her own application. The service will allow for many suitable adjustments and user-specific settings to adjust the behaviour and optimization goals (e.g. minimizing distance, maximizing resource utilization, etc.) through a comprehensive set of functions. This will enable you to gain control of the complete optimization processes.This service is based on JOpt (7.5.1-rc2-j17)
 *
 * The version of the OpenAPI document: 1.2.8-alpha-SNAPSHOT)
 * Contact: info@dna-evolutions.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// The stayOutCycleDefinition
    /// </summary>
    [DataContract(Name = "StayOutCycleDefinition")]
    public partial class StayOutCycleDefinition : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StayOutCycleDefinition" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StayOutCycleDefinition() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StayOutCycleDefinition" /> class.
        /// </summary>
        /// <param name="cycleLenght">The cycleLenght (required).</param>
        /// <param name="cycleStart">The cycleStart (required).</param>
        public StayOutCycleDefinition(string cycleLenght = default(string), DateOnly cycleStart = default(DateOnly))
        {
            // to ensure "cycleLenght" is required (not null)
            if (cycleLenght == null)
            {
                throw new ArgumentNullException("cycleLenght is a required property for StayOutCycleDefinition and cannot be null");
            }
            this.CycleLenght = cycleLenght;
            // to ensure "cycleStart" is required (not null)
            if (cycleStart == null)
            {
                throw new ArgumentNullException("cycleStart is a required property for StayOutCycleDefinition and cannot be null");
            }
            this.CycleStart = cycleStart;
        }

        /// <summary>
        /// The cycleLenght
        /// </summary>
        /// <value>The cycleLenght</value>
        /// <example>PT7D</example>
        [DataMember(Name = "cycleLenght", IsRequired = true, EmitDefaultValue = true)]
        public string CycleLenght { get; set; }

        /// <summary>
        /// The cycleStart
        /// </summary>
        /// <value>The cycleStart</value>
        [DataMember(Name = "cycleStart", IsRequired = true, EmitDefaultValue = true)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateOnly CycleStart { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StayOutCycleDefinition {\n");
            sb.Append("  CycleLenght: ").Append(CycleLenght).Append("\n");
            sb.Append("  CycleStart: ").Append(CycleStart).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
