/*
 * DNA Evolutions - JOpt.TourOptimizer
 *
 * This is DNA's JOpt.TourOptimizer service. A RESTful Spring Boot application using springdoc-openapi and OpenAPI 3. JOpt.TourOptimizer is a service that delivers route optimization and automatic scheduling features to be easily integrated into any third-party application. JOpt.TourOptimizer encapsulates all necessary optimization functionality and provides a comprehensive REST API that offers a domain-specific optimization interface for the transportation industry. The service is stateless and does not come with graphical user interfaces, map depiction or any databases. These extensions and adjustments are supposed to be introduced by the consumer of the service while integrating it into his/her own application. The service will allow for many suitable adjustments and user-specific settings to adjust the behaviour and optimization goals (e.g. minimizing distance, maximizing resource utilization, etc.) through a comprehensive set of functions. This will enable you to gain control of the complete optimization processes.This service is based on JOpt (7.5.3-j17)
 *
 * The version of the OpenAPI document: 1.3.3-SNAPSHOT
 * Contact: info@dna-evolutions.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ILoadCapacity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ILoadCapacityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ILoadCapacity
        //private ILoadCapacity instance;

        public ILoadCapacityTests()
        {
            // TODO uncomment below to create an instance of ILoadCapacity
            //instance = new ILoadCapacity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ILoadCapacity
        /// </summary>
        [Fact]
        public void ILoadCapacityInstanceTest()
        {
            // TODO uncomment below to test "IsType" ILoadCapacity
            //Assert.IsType<ILoadCapacity>(instance);
        }

        /// <summary>
        /// Test deserialize a DegradingLoadCapacity from type ILoadCapacity
        /// </summary>
        [Fact]
        public void DegradingLoadCapacityDeserializeFromILoadCapacityTest()
        {
            // TODO uncomment below to test deserialize a DegradingLoadCapacity from type ILoadCapacity
            //Assert.IsType<ILoadCapacity>(JsonConvert.DeserializeObject<ILoadCapacity>(new DegradingLoadCapacity().ToJson()));
        }

        /// <summary>
        /// Test deserialize a SimpleLoadCapacity from type ILoadCapacity
        /// </summary>
        [Fact]
        public void SimpleLoadCapacityDeserializeFromILoadCapacityTest()
        {
            // TODO uncomment below to test deserialize a SimpleLoadCapacity from type ILoadCapacity
            //Assert.IsType<ILoadCapacity>(JsonConvert.DeserializeObject<ILoadCapacity>(new SimpleLoadCapacity().ToJson()));
        }

        /// <summary>
        /// Test the property 'MaximalIndividualLoadCapacity'
        /// </summary>
        [Fact]
        public void MaximalIndividualLoadCapacityTest()
        {
            // TODO unit test for the property 'MaximalIndividualLoadCapacity'
        }

        /// <summary>
        /// Test the property 'CurrentLoad'
        /// </summary>
        [Fact]
        public void CurrentLoadTest()
        {
            // TODO unit test for the property 'CurrentLoad'
        }

        /// <summary>
        /// Test the property 'LoadPickupTime'
        /// </summary>
        [Fact]
        public void LoadPickupTimeTest()
        {
            // TODO unit test for the property 'LoadPickupTime'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'TypeName'
        /// </summary>
        [Fact]
        public void TypeNameTest()
        {
            // TODO unit test for the property 'TypeName'
        }
    }
}
